baseURL = 'https://weiseguy.net/'
defaultContentLanguage = "en"
languageCode = "en-us"

title = 'Weiseguy'
theme = 'gokarna'

[params]
  avatarURL = "/images/avatar.png"
  description = "The Journey from Sys Admin to Dev Ops"
  ShowBackToTopButton = true
  metaKeywords = ["blog", "gokarna", "hugo"]

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false


[menu]
  [[menu.main]]
    identifier = "Home"
    url = "https://weiseguy.net"
    name = "Home"
    pre = "<span data-feather='home'></span>"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    url = "/posts/"
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    url = "/tags/"
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    weight = 3
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/weiseguy1"
    weight = 4
    pre = "<span data-feather='github'></span>"
